name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Release
      run: cargo build --release --verbose
    - name: Upload Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: chisel-release
        path: target/release/chisel
        retention-days: 30
