name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write 

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: Build
        run: cargo build --release
        
      # Añadimos un paso para verificar los archivos generados
      - name: List files
        run: ls -la target/release/
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/clean-cli # Corregido el nombre del archivo
          draft: false
          prerelease: false
          generate_release_notes: true # Esto generará notas de release automáticamente
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
